### ISSUE TITLE
Problemas con la sala de espera

### ISSUE THREAD

**Issue by 801950** [UNIZAR-30226-2022-07/Frontend-Web#10]
La sala de espera da algún problema, no está creando una partida nueva cuando vuelve atrás y ocurre lo siguiente:
![image](https://user-images.githubusercontent.com/91154937/167930303-8d7e53df-cc22-4add-957f-563e75c8617e.png)

**Comment by 801950** [comment]
No aparecen las cartas que se juegan :(

**Comment by SrHeli0s** [comment]
Solucionados errores visuales

**Comment by SrHeli0s** [comment]
Solucionado todo, ahora sale una pequeña notificacion :)
![image](https://user-images.githubusercontent.com/75946421/168052451-fd932efa-bdc3-4162-a3aa-e793af026f8e.png)
