### ISSUE TITLE
Jugar cartas

### ISSUE THREAD

**Issue by 801950** [UNIZAR-30226-2022-07/Frontend-Web#18]
Al jugar una carta, si no es tu turno, no aparece en la pila del medio, pero desaparece de la mano del jugador, se debería mantener en la mano del jugador si se recibe un mensaje de que no se puede jugar.

**Comment by 801950** [comment]
Al usuario que actúa como host si que se le están actualizando la cantidad de cartas que tiene cada usuario, pero al contrincante no se le están actualizando correctamente.

**Comment by SrHeli0s** [comment]
estamos en ello :)

**Comment by SrHeli0s** [comment]
solucionado (creo)
