### ISSUE TITLE
Inicio de la partida

### ISSUE THREAD

**Issue by 801950** [UNIZAR-30226-2022-07/Frontend-Web#26]
Si la primera carta a jugar es +2 no se suman 2 cartas al jugador que empieza.
Deberían sumarle 2 cartas y pasar su turno

**Comment by SrHeli0s** [comment]
Añado:
Cualquier acción que se tenga que tomar automaticamente (robar, saltar turno, etc...) al inicio de la partida no se hace

**Comment by SrHeli0s** [comment]
Solucionado
