### ISSUE TITLE
Ranking nacional

### ISSUE THREAD

**Issue by 801950** [UNIZAR-30226-2022-07/Frontend-Web#32]
Se muestra mal el ranking nacional, devuelve los jugadores en orden pero no se está mostrando bien la cantidad de puntos que tiene cada uno.
Se muestra que todos tienen la misma cantidad de puntos que el usuario que ocupa el primer lugar del ranking.
![image](https://user-images.githubusercontent.com/91154937/168585235-ebb6cac1-1ccf-44d9-ba93-c7bc4f0f52e0.png)
![image](https://user-images.githubusercontent.com/91154937/168585720-723a62e0-f067-4bb5-a495-ad60cb35f3ca.png)

**Comment by viictorgallardo** [comment]
Buenos días, desde el departamento de Desarrollo Web queríamos pedir disculpas por si este infortunio ha provocado problemas. Me complace anunciar que ya esta solucionado,

Un saludo,
Encargado del desarrollo web del sistema.
