### ISSUE TITLE
+4

### ISSUE THREAD

**Issue by 801950** [UNIZAR-30226-2022-07/Frontend-Web#33]
Cuando un usuario tiene 2 cartas de +4 en la mano y juega uno con un color, el que tiene en la mano aún se le pone tb de ese color

**Comment by 801950** [comment]
![image](https://user-images.githubusercontent.com/91154937/168654159-12fb6dd2-d7aa-48dc-8e32-6bb58a370d03.png)

**Comment by SrHeli0s** [comment]
Estamos en ello

**Comment by SrHeli0s** [comment]
Pasa tambien con cualquier carta que se pueda cambiar de color (wild)

**Comment by SrHeli0s** [comment]
No tenemos ni idea de porque pasa

**Comment by SrHeli0s** [comment]
Vuelve a pasar y ni idea de porque
