### ISSUE TITLE
Volver a conectarse a una partida

### ISSUE THREAD

**Issue by 801950** [UNIZAR-30226-2022-07/Frontend-Web#55]
Si un usuario está jugando una partida y cierra el navegador, y lo vuelve a abrir, debería mostrarle la partida para continuar jugando, pero muestra el menú inicial, por lo que no estamos cumpliendo el requisito de retomar una partida.

**Comment by SrHeli0s** [comment]
Todavía no está hecho, esta pendiente para el domingo
Queremos terminar torneos antes porque depende de si estamos en un torneo o no hay que tomar unas acciones o otras (pedir el id de al final, decir que ganaste el torneo, etc...)
