### ISSUE TITLE
Bug visual numero de cartas Crazy 7

### ISSUE THREAD

**Issue by saladito** [UNIZAR-30226-2022-07/Frontend-Web#64]
Cuando se cambia la mano con Crazy 7 en el momento en el que se juega el 7 se cambian las manos correctamente, pero el número de cartas del jugador con el que has cambiado la mano no cambia en ese turno, cambia al siguiente.

**Comment by SrHeli0s** [comment]
La lógica del crazy seven es una movida
No pongo wontfix, pero es de baja prioridad
